config/routes.rb
Owgm::Application.routes.draw do

  devise_for :users
  resources :users

  resources :access_points, :only => [:index] do
    collection do
      post 'change_property' => 'access_points#batch_change_property'
      get 'select_group' => 'access_points#batch_select_group'
    end
  end

  resources :configurations, :only => [:edit, :update]

  resources :wisps, :only => :index do

    match 'reset_favourites' => 'access_points#reset_favourites', :as => :reset_favourites
    match 'access_points_favourite' => 'access_points#index', :as => :access_points_favourite, :defaults => { :filter => 'favourite' }

    member do
      get 'select_group' => 'access_points#batch_select_group'
    end

    match 'groups' => 'groups#list', :as => :groups, :via => [:get]
    match 'groups/:group_id/access_points' => 'access_points#index', :as => :group_access_points, :via => [:get]

    resources :access_points, :only => [:index, :show] do

      resource :property_set, :only => :update

      member do
        post 'toggle_public'
        post 'toggle_favourite'
        get 'last_logins'
      end
    end

    resources :activity_histories, :only => :index

    match 'access_points/:access_point_id/activities' => 'activities#show', :as => :access_point_activities
    match 'access_points/:access_point_id/activity_histories' => 'activity_histories#show', :as => :access_point_activity_histories
    match 'access_points/:access_point_id/associated_user_counts' => 'associated_user_counts#show',
          :as => :associated_user_counts
    match 'access_points/:access_point_id/associated_user_count_histories' => 'associated_user_count_histories#show',
          :as => :associated_user_count_histories
    match 'availability_report' => 'activity_histories#index', :as => :availability_report
    match 'export' => 'activity_histories#export', :as => :export, :via => [:post]
    match 'send_report' => 'activity_histories#send_report', :as => :send_report

    match 'access_points/:access_point_id/select_group' => 'access_points#select_group', :as => :access_point_select_group, :via => [:get]
    match 'access_points/:access_point_id/change_group/:group_id' => 'access_points#change_group', :as => :access_point_change_group, :via => [:post]
    match 'access_points/:access_point_id/edit_ap_alert_settings' => 'access_points#edit_ap_alert_settings', :as => :access_point_edit_ap_alert_settings, :via => [:post]

    match 'stats/logins.json' => 'stats#logins', :as => :logins_json, :via => [:get]
    match 'stats/traffic.json' => 'stats#traffic', :as => :traffic_json, :via => [:get]
    match 'stats/export' => 'stats#export', :as => :export_stats, :via => [:post]

    match 'stats/activities.json' => 'stats#activities', :as => :activities_json, :via => [:get]
  end

  resources :groups, :only => [:index, :new, :edit, :create, :update, :destroy] do
    member do
      post 'toggle_monitor'
      post 'toggle_count_stats'
    end
  end

  match 'wisps/' => 'wisps#index', :via => [:get]

  root :to => "application#index"

end

app/models/wisp.rb
# This file is part of the OpenWISP Geographic Monitoring
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class Wisp < ActiveRecord::Base
  acts_as_authorization_object

  has_many :access_points
  has_many :groups, :dependent => :destroy

  delegate :up, :down, :known, :unknown, :favourite, :to => :access_points, :prefix => true

  def to_param
    "#{name.downcase.gsub(/[^a-z0-9]+/i, '-')}"
  end

  def slug
    name.gsub(' ', '-').downcase
  end

  def owmw_enabled?
    Configuration.get(:owmw_enabled) && (
      Configuration.get(:wisps_with_owmw).include?(name) ||
      # support names containing spaces too
      Configuration.get(:wisps_with_owmw).include?(slug)
    )
  end

  # determin if owums is enabled for this wisp
  def owums_enabled?
    begin
      CONFIG['owums'].include?(slug)
    rescue NoMethodError
      return false
    end
  end

  # return owums base url of wisp or nil if not set
  def owums_url
    if owums_enabled?
      return CONFIG['owums'][slug]['url']
    else
      return nil
    end
  end

  # return owums username of wisp or nil if not set
  def owums_username
    if owums_enabled?
      return CONFIG['owums'][slug]['username']
    else
      return nil
    end
  end

  # return owums password of wisp or nil if not set
  def owums_password
    if owums_enabled?
      return CONFIG['owums'][slug]['password']
    else
      return nil
    end
  end

  # determine if datawarehouse is enabled for this wisp
  def datawarehouse_enabled?
    begin
      CONFIG['datawarehouse'].include?(slug)
    rescue NoMethodError
      return false
    end
  end

  # return datawarehouse base url of wisp or nil if not set
  def datawarehouse_url
    if datawarehouse_enabled?
      return CONFIG['datawarehouse'][slug]['url']
    else
      return nil
    end
  end

  # return datawarehouse username of wisp or nil if not set
  def datawarehouse_username
    if datawarehouse_enabled?
      return CONFIG['datawarehouse'][slug]['username']
    else
      return nil
    end
  end

  # return datawarehouse password of wisp or nil if not set
  def datawarehouse_password
    if datawarehouse_enabled?
      return CONFIG['datawarehouse'][slug]['password']
    else
      return nil
    end
  end

  # create unassigned roles for this wisp
  def create_roles
    roles = User.available_roles
    new_roles = []
    roles.each do |role|
      next if role == :wisps_viewer
      unless Role.where({:authorizable_id => self.id, :name => role.to_s}).length > 0
        new_roles << Role.create({:authorizable_type => 'Wisp', :name => role.to_s, :authorizable_id => self.id})
      end
    end
    new_roles
  end

  # the following method takes in consideration the "count_stats" column of the table group
  # only access points with following conditions are counted:
  #   * access points assigned to a group which has "count_stats" == true are counted
  #   * access points with no property set record associated
  def count_access_points(action=:total)
    groups_where = 'groups.count_stats IS NULL OR groups.count_stats = 1'

    case action.to_sym
    when :total
      # all indipendently on the value of reachable
      property_sets_where = false
    when :up
      # only reachable ap
      property_sets_where = { :property_sets => { :reachable => true } }
    when :down
      # only unreachable ap
      property_sets_where = { :property_sets => { :reachable => false } }
    when :unknown
      # only unknown .. it means it has no property set yet
      property_sets_where = { :property_sets => { :reachable => nil } }
    when :favourite
      # favourites of this wisp
      property_sets_where = { :property_sets => { :favourite => true } }
    else
      raise ArgumentError, 'unknown action argument "%s", can be only "total", "up", "down", "unknown" or "favourite"' % action
    end

    # scope the query so we can add more restrictions to the lookup if needed
    query = AccessPoint.with_properties_and_group('groups.count_stats').of_wisp(self).where(groups_where).scoped
    # in all the cases except total
    if property_sets_where
      query = query.where(property_sets_where)
    end

    # return count only
    return query.count()
  end

  # count groups of wisp
  def count_groups
    return Group.where(['wisp_id = ? OR wisp_id IS NULL', self.id]).count()
  end

  ### Static methods ###

  # creates are roles if missing
  def self.create_all_roles
    self.all.each do |wisp|
      wisp.create_roles
    end
  end

  # creates all roles if it finds a number of roles that is less than expected
  # is run automatically when displaying "edit user" and "new user" pages
  def self.create_all_roles_if_necessary
    wisps = Wisp.count
    roles = Role.count
    if roles < wisps * 5 + 1
      self.create_all_roles
    end
  end

  def self.collection(user)
    collection = []
    is_wisp_viewer = user.roles_include?(:wisps_viewer)
    Wisp.select([:id, :name]).all.each do |wisp|
      collection << [wisp.name, wisp.id] if is_wisp_viewer or user.roles_include?(:wisp_access_points_viewer, wisp.id)
    end
    collection
  end

  # select wisps accessible to user
  def self.all_accessible_to(user)
    if user.nil?
      return []
    end
    # if user has role "wisps_viewer" he can see all the groups
    if user.has_role?(:wisps_viewer)
      Wisp.all
    else
      # if user has any role "wisp_access_points_viewer" of some specific wisp return those wisp
      wisp_id_list = user.roles_search(:wisp_access_points_viewer).map{ |role| role.authorizable_id }
      unless wisp_id_list.length <= 0
        Wisp.find(wisp_id_list)
      else
        # if user has neither wisps_viewer nor wisp_access_points_viewer roles return an empty list
        []
      end
    end
  end
end

app/controllers/wisps_controller.rb
# This file is part of the OpenWISP Geographic Monitoring
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class WispsController < ApplicationController
  before_filter :authenticate_user!

  access_control do
    default :deny

    action :index do
      allow :wisps_viewer
      allow :wisp_access_points_viewer, :of => :wisp
    end
  end

  def index
    @wisps = Wisp.all
    wisp_breadcrumb(force=true)
  end

  
end

app/views/wisps/index.html.erb
<%#
# This file is part of the OpenWISP Geographic Monitoring
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_12">
  <div class="box">
    <h1><%=t :Wisp_list %></h1>

    <table id="wisp-list">
      <thead>
        <tr>
          <th class="name"><%=t :Name %></th>
          <th class="notes"><%=t :Notes %></th>
          <th class="up green center"><%=t :Up %></th>
          <th class="down red center"><%=t :Down %></th>
          <th class="unknown center"><%=t :Unknown %></th>
          <th class="total center"><%=t :Total %></th>
          <th class="favourite center"><%= image_tag('star.png', :alt => 'favourite') %><span><%=t :Favourites %></span></th>
          <th class="groups center"><%=t :Groups %></th>
          <th class="report">&nbsp;</th>
        </tr>
      </thead>

      <tbody>
      <% @wisps.each do |wisp| %>
          <% if auth?(:wisps_viewer) || auth?(:wisp_access_points_viewer, wisp) %>
              <tr class="<%= cycle 'odd', 'even' %>">
                <td class="name"><%= link_to wisp.name, wisp_access_points_path(wisp) %></td>
                <td class="notes"><%= wisp.notes %></td>
                <td class="up center"><%= wisp.count_access_points(:up) %></td>
                <td class="down center"><%= wisp.count_access_points(:down) %></td>
                <td class="unknown center"><%= wisp.count_access_points(:unknown) %></td>
                <td class="total center"><%= wisp.count_access_points(:total) %></td>
                <td class="favourite center">
                  <%= link_to wisp.count_access_points(:favourite), wisp_access_points_favourite_path(wisp),
                    :class => 'hastip',
                    :title => t(:View_favourite_of_wisp, :wisp => wisp.name)
                  %>
                </td>
                <td class="groups center">
                  <%= link_to wisp.count_groups, wisp_groups_path(wisp),
                    :class => 'hastip',
                    :title => t(:View_groups_of_wisp, :wisp => wisp.name) %>
                </td>
                <td class="report center"><%= link_to t(:Availability_report), wisp_availability_report_path(wisp) %></td>
              </tr>
          <% end %>
      <% end %>
      </tbody>
    </table>

  </div>
</div>