config/routes.rb
Owgm::Application.routes.draw do

  devise_for :users
  resources :users

  resources :access_points, :only => [:index] do
    collection do
      post 'change_property' => 'access_points#batch_change_property'
      get 'select_group' => 'access_points#batch_select_group'
    end
  end

  resources :configurations, :only => [:edit, :update]

  resources :wisps, :only => :index do

    match 'reset_favourites' => 'access_points#reset_favourites', :as => :reset_favourites
    match 'access_points_favourite' => 'access_points#index', :as => :access_points_favourite, :defaults => { :filter => 'favourite' }

    member do
      get 'select_group' => 'access_points#batch_select_group'
    end

    match 'groups' => 'groups#list', :as => :groups, :via => [:get]
    match 'groups/:group_id/access_points' => 'access_points#index', :as => :group_access_points, :via => [:get]

    resources :access_points, :only => [:index, :show] do

      resource :property_set, :only => :update

      member do
        post 'toggle_public'
        post 'toggle_favourite'
        get 'last_logins'
      end
    end

    resources :activity_histories, :only => :index

    match 'access_points/:access_point_id/activities' => 'activities#show', :as => :access_point_activities
    match 'access_points/:access_point_id/activity_histories' => 'activity_histories#show', :as => :access_point_activity_histories
    match 'access_points/:access_point_id/associated_user_counts' => 'associated_user_counts#show',
          :as => :associated_user_counts
    match 'access_points/:access_point_id/associated_user_count_histories' => 'associated_user_count_histories#show',
          :as => :associated_user_count_histories
    match 'availability_report' => 'activity_histories#index', :as => :availability_report
    match 'export' => 'activity_histories#export', :as => :export, :via => [:post]
    match 'send_report' => 'activity_histories#send_report', :as => :send_report

    match 'access_points/:access_point_id/select_group' => 'access_points#select_group', :as => :access_point_select_group, :via => [:get]
    match 'access_points/:access_point_id/change_group/:group_id' => 'access_points#change_group', :as => :access_point_change_group, :via => [:post]
    match 'access_points/:access_point_id/edit_ap_alert_settings' => 'access_points#edit_ap_alert_settings', :as => :access_point_edit_ap_alert_settings, :via => [:post]

    match 'stats/logins.json' => 'stats#logins', :as => :logins_json, :via => [:get]
    match 'stats/traffic.json' => 'stats#traffic', :as => :traffic_json, :via => [:get]
    match 'stats/export' => 'stats#export', :as => :export_stats, :via => [:post]

    match 'stats/activities.json' => 'stats#activities', :as => :activities_json, :via => [:get]
  end

  resources :groups, :only => [:index, :new, :edit, :create, :update, :destroy] do
    member do
      post 'toggle_monitor'
      post 'toggle_count_stats'
    end
  end

  match 'wisps/' => 'wisps#index', :via => [:get]

  root :to => "application#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :wisp
  has_many :property_set, :dependent => :nullify
  
  validates_presence_of :name
  
  validates :alerts_threshold_down,
            :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 },
            :allow_blank => true
  
  validates :alerts_threshold_up,
            :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 },
            :allow_blank => true
  
  validates :alerts_email, :multiple_email => true, :allow_blank => true
  
  validate :if_alerts_activated_no_empty_alert_fields
  
  before_destroy :is_default_group?
  
  def up
    count_stats ? self.attributes['up'] : 'N/A'
  end
  
  def down
    count_stats ? self.attributes['down'] : 'N/A'
  end
  
  def unknown
    count_stats ? self.attributes['unknown'] : 'N/A'
  end
  
  def favourite
    AccessPoint.favourite(:total, self.wisp_id, self.id).count
  end
  
  def monitor!
    self.monitor = !self.monitor
    self.save
    self.monitor
  end
  
  def count_stats!
    self.count_stats = !self.count_stats
    self.save
    self.count_stats
  end
  
  # update group statistics
  def update_counts()
    self.total = PropertySet.where(:group_id => self.id).count
    # up, down and unknown will be updated only if monitoring == true
    if self.monitor
      self.up = PropertySet.where(:group_id => self.id, :reachable => 1).count
      self.down = PropertySet.where(:group_id => self.id, :reachable => 0).count
      self.unknown = PropertySet.where(:group_id => self.id, :reachable => nil).count
    end
    save!
  end
  
  # update statistics for all groups
  def self.update_all_counts()
    self.all.each do |group|
      group.update_counts()
    end
  end
  
  # DB query
  def self.all_join_wisp(where=nil, params=[])
    if where.nil?: where = '1=1'; end
    self.find_by_sql(["SELECT groups.*, wisps.name AS wisp_name FROM groups
                    LEFT JOIN wisps ON wisps.id = groups.wisp_id
                    WHERE #{where}
                    ORDER BY wisp_id"] + params)
  end
  
  # select groups accessible to user
  def self.all_accessible_to(user)
    # if user has role "wisps_viewer" he can see all the groups
    if user.has_role?(:wisps_viewer)
      Group.all_join_wisp
    else
      # if user has any role "wisp_access_points_viewer" of some specific wisp he can see all the groups of those wisps
      where_clause = 'wisp_id IS NULL'
      wisps_id = []
      user.roles_search(:wisp_access_points_viewer).each do |role|
        where_clause << ' OR wisp_id = ?'
        wisps_id << role.authorizable_id
      end
      unless wisps_id.length <= 0
        Group.all_join_wisp(where_clause, wisps_id)
      else
        # if user has neither wisps_viewer nor wisp_access_points_viewer roles he can't see any group
        []
      end
    end
  end
  
  private

  def is_default_group?
    errors.add(:base, I18n.t("Cannot_delete_default_group")) unless self.id != 1
    errors.blank?
  end
  
  def if_alerts_activated_no_empty_alert_fields
    if alerts
      if alerts_email.blank?
        errors.add(:alerts_email, I18n.t(:alerts_email_not_blank_if))
      end
      
      if alerts_threshold_down.blank?
        errors.add(:alerts_threshold_down, I18n.t(:alerts_threshold_down_not_blank_if))
      end
      
      if alerts_threshold_up.blank?
        errors.add(:alerts_threshold_up, I18n.t(:alerts_threshold_up_not_blank_if))
      end
    end    
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_wisp, :wisp_breadcrumb, :only => [:list]
  
  skip_before_filter :verify_authenticity_token, :only => [:toggle_monitor, :toggle_count_stats]
  
  access_control do
    default :deny
    allow :wisps_viewer
    
    actions :list do
      allow :wisp_access_points_viewer, :of => :wisp, :if => :wisp_loaded?
    end
    
    actions :index, :new, :create, :update, :edit, :destroy, :toggle_monitor, :toggle_count_stats do
      allow :wisp_access_points_viewer
    end
  end
  
  def index
    @groups = Group.all_accessible_to(@current_user)
    
    add_breadcrumb(I18n.t(:Group_list), groups_url)
  end
  
  def list
    @groups = Group.all_join_wisp('wisp_id IS NULL OR wisp_id = ?', [@wisp.id])
    
    add_breadcrumb(I18n.t(:Group_list_of_wisp, :wisp => @wisp.name), wisp_groups_path(@wisp))
  end
  
  def new
    @group = Group.new
    
    add_breadcrumb(I18n.t(:Group_list), groups_url)
    add_breadcrumb(I18n.t(:New_group), new_group_url)
  end
  
  def create
    @group = Group.new(params[:group])

    if @group.save
      flash[:notice] = t(:Group_created)
      redirect_to(groups_url)
    else
      render :action => "new"
    end
  end
  
  def update
    @group = Group.find(params[:id])

    if @group.update_attributes(params[:group])
      flash[:notice] = t(:Group_modified, :group => @group.name)
      redirect_to(groups_url)
    else
      render :action => "edit"
    end
  end
  
  def edit
    @group = Group.find(params[:id])
    
    add_breadcrumb(I18n.t(:Group_list), groups_url)
    add_breadcrumb('%s "%s"' % [I18n.t(:Edit_group), @group.name], edit_group_url(@group.id))
  end
  
  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to(groups_url)
  end
  
  def toggle_monitor
    group = Group.find(params[:id])
    group.monitor!
    respond_to do |format|
      format.json{
        image = view_context.image_path(group.monitor ? 'accept.png' : 'delete.png')
        render :json => { 'monitor' => group.monitor, 'image' => image }
      }
    end
  end
  
  def toggle_count_stats
    group = Group.find(params[:id])
    group.count_stats!
    respond_to do |format|
      format.json{
        image = view_context.image_path(group.count_stats ? 'accept.png' : 'delete.png')
        render :json => { 'count_stats' => group.count_stats, 'image' => image }
      }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  
  # returns POST value if any
  # otherwise returns value from DB if any
  # otherwise returns general default value (from CONFIG)
  def alerts_placeholder(group, field)
    value = group.attributes[field]
    
    param = params[:group][field.to_sym] rescue nil
    
    if param
      return param
    elsif value.nil?
      return CONFIG[field]
    else
      return value
    end
  end
  
end

app/views/groups/_form.html.erb
<% content_for :after_defaults do %>
    <%= javascript_include_tag 'jquery-ui.js', 'jquery.tagit.js' %>
    <%= stylesheet_link_tag 'jquery-ui/styles.css', 'jquery.tagit.css' %>
<% end %>

<%= form_for @group do |f| %>
    <fieldset id="group_form">
        <legend><strong><%= @group.new_record? ? t(:New_group) : t(:Edit_group) %></strong></legend>
        <p><%= f.error_messages %></p>
        <div class="field">
            <strong><%= label_tag :wisp, t(:Wisp) %>:</strong>
            <%= f.select(:wisp_id, Wisp.collection(@current_user)) %>
        </div>
        <div class="field">
            <strong><%= label_tag :group_name, t(:Name) %>:</strong>
            <%= f.text_field :name %>
        </div>
        
        <div class="field">
            <strong><%= label_tag :group_description, t(:Description) %>:</strong><br />
            <%= f.text_area :description %>
        </div>
        
        <div class="field">
            <p><strong><%= label_tag :group_monitor, t(:Monitor) %>:</strong> <%= f.check_box :monitor %></p>
            <p><span class="help"><%= t :Monitor_help %>.</span></p>
        </div>
        
        <div class="field">
            <p><strong><%= label_tag :group_count_stats, t(:Count_stats) %>:</strong> <%= f.check_box :count_stats %></p>
            <p><span class="help"><%= t :Count_stats_help %>.</span></p>
        </div>

        <% if @group.id != 1 %>
        <fieldset id="alert-settings" class="subgroup hidden">
            <legend><%= t :Alert_settings %></legend>
            <div class="field">
                <%= label_tag :group_alerts, t(:Alerts_active) %>
                
                <div class="right">
                    <%= f.check_box :alerts %>
                    <span class="help"><%= t :Alerts_active_help_text %></span>
                </div>
            </div>
            
            <div class="field">
                <%= label_tag :group_alerts_email, t(:Email_addresses) %>
                
                <div class="right">
                    <%= f.text_field :alerts_email, :value => alerts_placeholder(@group, 'alerts_email') %>
                    <span class="help"><%= t :Alerts_email_help_text %></span>
                </div>
            </div>
                
            <div class="field">
                <%= label_tag :group_alerts_threshold_down, t(:Threshold_down) %>
                
                <div class="right">
                    <%= f.number_field :alerts_threshold_down, :value => alerts_placeholder(@group, 'alerts_threshold_down'), :min => 0 %>
                    <span class="help"><%= t :Threshold_down_help_text %></span>
                </div>
            </div>
            
            <div class="field">
                <%= label_tag :group_alerts_threshold_up, t(:Threshold_up) %>
                
                <div class="right">
                    <%= f.number_field :alerts_threshold_up, :value => alerts_placeholder(@group, 'alerts_threshold_up'), :min => 0 %>
                    <span class="help"><%= t :Threshold_up_help_text %></span>
                </div>
            </div>
        </fieldset>
        <script>owgm.initGroupAlertSettings()</script>
        <% end %>
        
        <% unless @group.new_record? %>
        <div class="box" id="group_stats">
            <h2><%= t :Group_statistics %></h2>
            <p><strong><%= t(:Total_AP) %>:</strong> <%= @group.total %></p>
            <p><strong><%= t(:Total_AP_up) %>:</strong> <%= @group.up %></p>
            <p><strong><%= t(:Total_AP_down) %>:</strong> <%= @group.down %></p>
            <p><strong><%= t(:Created_at) %>:</strong> <%= @group.created_at.to_time.strftime('%e %B %Y - %l:%M %p') rescue nil %></p>
            <p><strong><%= t(:Updated_at) %>:</strong> <%= @group.updated_at.to_time.strftime('%e %B %Y - %l:%M %p') rescue nil %></p>
        </div>
        <% end %>
        
        <p>
        <% if @group.new_record? %>
            <%= f.submit t(:Create), :class => 'submit' %>
        <% else %>
            <%= f.submit t(:Edit), :class => 'submit' %>
        <% end %>
        </p>
    </fieldset>
<% end %>

app/views/groups/edit.html.erb
<div class="grid_12">
  <div class="box">
    <h2><%=t :Edit_group %> "<%= @group.name %>"</h2>
    <br />
    <%= render 'form' %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="grid_12">
  <div class="box">
    <h1><%=t :Group_list %></h1>
    <table id="group_list">
      <thead>
        <tr>
          <th class="name"><%=t :Name %></th>
          <th class="wisp"><%=t :Wisp %></th>
          <th class="center"><%=t :Monitor %></th>
          <th class="center"><%=t :Count_stats %></th>
          <th class="center"><%=t :Total_AP %></th>
          <th class="green center"><%=t :Up %></th>
          <th class="red center"><%=t :Down %></th>
          <th class="center"><%=t :Unknown %></th>
          <th class="center favourite"><%= image_tag('star.png', :alt => 'favourite') %><span><%=t :Favourites %></span></th>
          <th class="center"><%=t :View_AP %></th>
          <th class="center"><%=t :Actions %></th>
        </tr>
      </thead>
      <tbody>
      <% @groups.each do |group| %>
        <tr class="<%= cycle 'odd', 'even' %>">
          <td class="name"><%= link_to group.name, edit_group_url(group.id) %></td>
          <td class="wisp"><%= group.wisp_name %></td>
          <td class="monitor center">
            <a class="toggle-monitor" data-href="<%= toggle_monitor_group_path(group.id) %>">
              <img src="<%= image_path(group.monitor ? 'accept.png' : 'delete.png') %>" alt="">
            </a>
          </td>
          <td class="count-stats center">
            <a class="toggle-count-stats" data-href="<%= toggle_count_stats_group_path(group.id) %>">
              <img src="<%= image_path(group.count_stats ? 'accept.png' : 'delete.png') %>" alt="">
            </a>
          </td>
          <td class="total center"><%= group.total %></td>
          <td class="total_up center"><%= group.up %></td>
          <td class="total_down center"><%= group.down %></td>
          <td class="total_unkown center"><%= group.unknown %></td>
          <td class="favourite center"><%= group.favourite %></td>
          <td class="view_ap center">
            <% if group.wisp_id %>
              <%= link_to t(:Access_points), wisp_group_access_points_path(slugify(group.wisp_name), group) %>
            <% end %>
          </td>
          <td class="center">
            <% if group.id != 1 %>
              <%= link_to t(:Delete), group_path(group), :method => :delete, :confirm => t(:Are_you_sure) %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <p><%= link_to t(:New_group), new_group_url, :class => 'button' %></p>    
  </div>
</div>
<script>owgm.initGroupList()</script>

app/views/groups/list.html.erb
<div class="grid_12">
  <div class="box">
    <h1><%=t :Group_list_of_wisp, :wisp => @wisp.name %></h1>
    <table id="group_list">
      <thead>
        <tr>
          <th class="name"><%=t :Name %></th>
          <th class="wisp"><%=t :Wisp %></th>
          <th class="center"><%=t :Monitor %></th>
          <th class="center"><%=t :Count_stats %></th>
          <th class="center"><%=t :Total_AP %></th>
          <th class="green center"><%=t :Up %></th>
          <th class="red center"><%=t :Down %></th>
          <th class="center"><%=t :Unknown %></th>
          <th class="center favourite"><%= image_tag('star.png', :alt => 'favourite') %><span><%=t :Favourites %></span></th>
        </tr>
      </thead>
      <tbody>
      <% @groups.each do |group| %>
        <tr class="<%= cycle 'odd', 'even' %>">
          <td class="name"><%= link_to group.name, wisp_group_access_points_path(@wisp, group) %></td>
          <td class="wisp"><%= group.wisp_name %></td>
          <td class="monitor center">
            <img src="<%= image_path(group.monitor ? 'accept.png' : 'delete.png') %>" alt="">
          </td>
          <td class="coount-stats center">
            <img src="<%= image_path(group.count_stats ? 'accept.png' : 'delete.png') %>" alt="">
          </td>
          <td class="total center"><%= group.total %></td>
          <td class="total_up center"><%= group.up %></td>
          <td class="total_down center"><%= group.down %></td>
          <td class="total_unkown center"><%= group.unknown %></td>
          <td class="favourite center"><%= group.favourite %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <p>
      <%= link_to t(:View_all_the_AP), wisp_access_points_path(@wisp), :class => 'button' %> &nbsp;
      <%= link_to t(:Manage_groups), groups_path, :class => 'button' %>
    </p>
  </div>
</div>

app/views/groups/new.html.erb
<div class="grid_12">
  <div class="box">
    <h2><%=t :New_group %></h2>
    <br />
    <%= render 'form' %>
  </div>
</div>