config/routes.rb
Owgm::Application.routes.draw do

  devise_for :users
  resources :users

  resources :access_points, :only => [:index] do
    collection do
      post 'change_property' => 'access_points#batch_change_property'
      get 'select_group' => 'access_points#batch_select_group'
    end
  end

  resources :configurations, :only => [:edit, :update]

  resources :wisps, :only => :index do

    match 'reset_favourites' => 'access_points#reset_favourites', :as => :reset_favourites
    match 'access_points_favourite' => 'access_points#index', :as => :access_points_favourite, :defaults => { :filter => 'favourite' }

    member do
      get 'select_group' => 'access_points#batch_select_group'
    end

    match 'groups' => 'groups#list', :as => :groups, :via => [:get]
    match 'groups/:group_id/access_points' => 'access_points#index', :as => :group_access_points, :via => [:get]

    resources :access_points, :only => [:index, :show] do

      resource :property_set, :only => :update

      member do
        post 'toggle_public'
        post 'toggle_favourite'
        get 'last_logins'
      end
    end

    resources :activity_histories, :only => :index

    match 'access_points/:access_point_id/activities' => 'activities#show', :as => :access_point_activities
    match 'access_points/:access_point_id/activity_histories' => 'activity_histories#show', :as => :access_point_activity_histories
    match 'access_points/:access_point_id/associated_user_counts' => 'associated_user_counts#show',
          :as => :associated_user_counts
    match 'access_points/:access_point_id/associated_user_count_histories' => 'associated_user_count_histories#show',
          :as => :associated_user_count_histories
    match 'availability_report' => 'activity_histories#index', :as => :availability_report
    match 'export' => 'activity_histories#export', :as => :export, :via => [:post]
    match 'send_report' => 'activity_histories#send_report', :as => :send_report

    match 'access_points/:access_point_id/select_group' => 'access_points#select_group', :as => :access_point_select_group, :via => [:get]
    match 'access_points/:access_point_id/change_group/:group_id' => 'access_points#change_group', :as => :access_point_change_group, :via => [:post]
    match 'access_points/:access_point_id/edit_ap_alert_settings' => 'access_points#edit_ap_alert_settings', :as => :access_point_edit_ap_alert_settings, :via => [:post]

    match 'stats/logins.json' => 'stats#logins', :as => :logins_json, :via => [:get]
    match 'stats/traffic.json' => 'stats#traffic', :as => :traffic_json, :via => [:get]
    match 'stats/export' => 'stats#export', :as => :export_stats, :via => [:post]

    match 'stats/activities.json' => 'stats#activities', :as => :activities_json, :via => [:get]
  end

  resources :groups, :only => [:index, :new, :edit, :create, :update, :destroy] do
    member do
      post 'toggle_monitor'
      post 'toggle_count_stats'
    end
  end

  match 'wisps/' => 'wisps#index', :via => [:get]

  root :to => "application#index"

end

app/controllers/access_points_controller.rb
# This file is part of the OpenWISP Geographic Monitoring
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class AccessPointsController < ApplicationController
  before_filter :authenticate_user!, :load_wisp, :wisp_breadcrumb

  skip_before_filter :verify_authenticity_token, :only => [
    :change_group,
    :toggle_public,
    :toggle_favourite,
    :batch_change_property,
    :erase_favourite,
    :edit_ap_alert_settings
  ]

  access_control do
    default :deny

    actions :index,:show, :change_group, :select_group, :toggle_public, :toggle_favourite,
            :batch_select_group, :favourite, :reset_favourites, :last_logins, :edit_ap_alert_settings do
      allow :wisps_viewer
      allow :wisp_access_points_viewer, :of => :wisp, :if => :wisp_loaded?
    end

    actions :batch_change_property do
      allow :wisps_viewer
      allow :wisp_access_points_viewer
    end
  end

  def index
    @showmap = CONFIG['showmap']
    @access_point_pagination = CONFIG['access_point_pagination']

    @favourite = params[:filter] == 'favourite' ? true : false

    # if group view
    if params[:group_id]
      begin
        @group = Group.select([:id, :wisp_id, :name, :monitor, :count_stats, :up, :down, :unknown, :total]).where(['wisp_id IS NULL or wisp_id = ?', @wisp.id]).find(params[:group_id])
      rescue ActiveRecord::RecordNotFound
        render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
        return
      end
    end

    respond_to do |format|
      format.any(:html, :js) { @access_points = access_points_with_sort_search_and_paginate.of_wisp(@wisp) }
      format.json {
		@access_points = access_points_with_filter.of_wisp(@wisp)
		# if not simple view call draw_map model method which does clusters
		if params[:simple].nil?
		  @access_points = @access_points.draw_map
		end
	  }
      format.rss { @access_points = AccessPoint.of_wisp(@wisp).on_georss }
    end

    crumb_for_group
    crumb_for_wisp
    crumb_for_access_point_favourite
  end

  def show
    @access_point = AccessPoint.with_properties_and_group.find(params[:id])
    @access_point.build_property_set_if_group_name_empty()

    ap_wisp = @access_point.wisp
    unless [ap_wisp.slug, ap_wisp.name, ap_wisp.id, ap_wisp.id.to_s].include?(params[:wisp_id])
	  render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
      return
	end

    @from = Date.strptime(params[:from], I18n.t('date.formats.default')) rescue 1.months.ago.to_date
    @to = Date.strptime(params[:to], I18n.t('date.formats.default')) rescue Date.today

    require "net/http"
	require "uri"
    crumb_for_wisp
    crumb_for_access_point
  end

  # retrieve latest logins and sessions that have been started from an AP
  def last_logins
    @access_point = AccessPoint.find(params[:id])
    # retrieve radius accountings
    RadiusSession.active_resource_from(@wisp.owums_url, @wisp.owums_username, @wisp.owums_password)
	@radius_sessions = RadiusSession.find(:all, :params => { :ap => @access_point.common_name, :last => 10 })
	render :layout => false
  end

  def select_group
    @access_point_id = params[:access_point_id]
    @groups = Group.all_join_wisp("wisp_id = ? OR wisp_id IS NULL", [@wisp.id])
    render :layout => false
  end

  def change_group
    # ensure AP and Group are correct otherwise return 404
    begin
      ap = AccessPoint.find(params[:access_point_id])
      # ensure group is a general group of specific of this wisp
      group = Group.select([:id, :name]).where(['wisp_id IS NULL or wisp_id = ?', @wisp.id]).find(params[:group_id])
    rescue ActiveRecord::RecordNotFound
      render :status => 404, :nothing => true
      return
    end
    # get or create property set
    property_set = ap.properties
    # change gorup, save and return json response
    property_set.group_id = group.id
    property_set.save!
    # update group counts (total, up, down, unknown)
    Group.update_all_counts()
    respond_to do |format|
      format.json { render :json => group.attributes }
    end
  end

  # toggle published AP in the GeoRSS xml
  def toggle_public
    ap = PropertySet.find_by_access_point_id(params[:id])
    ap.public = !ap.public?
    ap.save!
    respond_to do |format|
      format.json{
        image = view_context.image_path(ap.public ? 'accept.png' : 'delete.png')
        render :json => { 'public' => ap.public, 'image' => image }
      }
    end
  end

  # toggle favourite property
  def toggle_favourite
    ap = PropertySet.find_by_access_point_id(params[:id])
    ap.favourite = !ap.favourite?
    ap.save!
    respond_to do |format|
      format.json{
        image = view_context.image_path(ap.favourite ? 'star.png' : 'star-off.png')
        render :json => { 'favourite' => ap.favourite, 'image' => image }
      }
    end
  end

  def reset_favourites
    @access_points = AccessPoint.with_properties.where(:wisp_id => @wisp.id)

    @access_points.each do |ap|
      if ap.favourite?
        ap.property_set.update_attributes(:favourite => '0' )
      end
    end

    respond_to do |format|
      format.html { redirect_to wisp_access_points_favourite_path(@wisp) }
    end
  end

  def batch_select_group
    if wisp_loaded?
      @groups = Group.all_join_wisp("wisp_id = ? OR wisp_id IS NULL", [@wisp.id])
    else
      # maybe is too much! - for the moment it works so let's keep it
      if current_user.has_role?(:wisps_viewer)
        @groups = Group.all_join_wisp()
      else
        @groups = Group.all_accessible_to(current_user)
      end
    end
    render :template => 'access_points/select_group', :layout => false
  end

  def batch_change_property
    # parameters expected:
    # * access_points (array of IDs)
    # * property_name (string)
    # * property_value (string)
    access_points_ids = params[:access_points]
    property_name = params[:property_name]
    property_value = params[:property_value]

    # ensure all parameters are sent correctly otherwise return 400 bad request status code
    if property_name.nil? or property_name == '' or property_value.nil? or property_value == '' or access_points_ids.nil? or access_points_ids.length < 1
      render :status => 400, :json => { "details" => I18n.t(:Bad_format_parameters) }
      return
    end

    # get an array of id for which the user is authorized
    authorized_for_wisps = current_user.roles_search(:wisp_access_points_viewer).map { |r| r.authorizable_id }

    # in case user the array is empty, the user is wisps_viewer, because even if he is not wisp_access_points_viewer for any wisp
    # he was able to get here (otherwise he would have been blocked before because the acl rules on top)
    wisps_viewer = authorized_for_wisps.length < 1 ? true : false

    access_points = AccessPoint.with_properties.find(access_points_ids)

    case property_name
    when 'group_id'
      # ensure Group is correct otherwise return 404
      begin
        # ensure group is a general group of specific of this wisp
        group = Group.select([:id, :name, :wisp_id]).find(property_value)

        # if moving access points to a group of a specific wisp, user must be authorized for that wisp
        if not group.wisp_id.nil? and not wisps_viewer and not authorized_for_wisps.include?(group.wisp_id)
          render :status => 403, :json => { "details" => I18n.t(:User_does_not_have_permission) }
          return
        end
      rescue ActiveRecord::RecordNotFound
        render :status => 404, :json => { "details" => I18n.t(:Group_not_found) }
        return
      end
    when 'public'
    when 'favourite'
    # otherwise if supplying an unrecognized parameter for "property_name"
    else
      render :status => 400, :json => { "details" => I18n.t(:Unrecognized_property_name) }
      return
    end

    # perform checks first
    access_points.each do |ap|
      # user must be authorized for wisp_id of the access point he wants to edit
      if not wisps_viewer and not authorized_for_wisps.include?(ap.wisp_id)
        render :status => 403, :json => { "details" => I18n.t(:User_does_not_have_permission_ap_id, :ap_id => ap.id) }
        return
      end

      # wisp_id of access point must coincide with wisp_id of group (unless wisp_id of group is NULL)
      if property_name == 'group_id' and not group.wisp_id.nil? and not ap.wisp_id == group.wisp_id
        render :status => 403, :json => { "details" => I18n.t(:Moving_access_point_different_wisp_not_allowed, :wisp1 => ap.wisp.name, :wisp2 => group.wisp.name) }
        return
      end

      # ensure ap has property_sets related object
      if ap.attributes[property_name].nil?
        # create properties!
        ap.properties.save!
      end
    end

    AccessPoint.batch_change_property(access_points, property_name, property_value)

    if property_name == 'group_id' or property_name == 'favourite'
      # update group counts
      Group.update_all_counts()
    end

    render :status => 200, :json => { "details" => I18n.t(:Access_point_updated, :length => access_points.length) }
  end

  def edit_ap_alert_settings
	# get all AP info, needed for comparing
	ap = AccessPoint.with_properties_and_group.find(params[:access_point_id])
	# get properties object, needed for saving eventual changes
	properties = PropertySet.find_by_access_point_id(params[:access_point_id])

	# nothing has been changed yet

app/helpers/access_point_helper.rb
# This file is part of the OpenWISP Geographic Monitoring
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

module AccessPointHelper
  def categories_select_data(wisp, access_point)    
    data = PropertySet.categories(wisp)
    data.compact! # remove nil
    data.delete("") # remove ""
    # prepare list for javascript
    data = data.map do |category|
      "'#{escape_javascript(category)}':'#{escape_javascript(category)}'" unless category.blank?
    end
    data << "'': '#{t :None}'"
    data << "'!new!': '#{t :Create_new_category}'"
    # return javascript object with list of categories
    "{#{data.join(',')}}"
  end

  def image_path_for(marker)
    image = ''

    if marker.is_a? AccessPoint
      image = 'ap_'
    elsif marker.is_a? Cluster
      image = 'cluster_'
    end

    if marker.unknown? or !marker.monitor?
      image += 'unknown.png'
    elsif marker.up?
      image += 'up.png'
    elsif marker.down?
      image += 'down.png'
    end

    image_path(image)
  end

  def image_tag_for(marker, opts={})
    image_tag image_path_for(marker), opts
  end
  
  def select_group_data_href(wisp, access_point_id, group_id)
    unless access_point_id.nil?
      ("data-href=\"%s\"" % [wisp_access_point_change_group_path(wisp, access_point_id, group_id)]).html_safe
    end
  end
  
  def link_to_group(group_name, wisp, group_id)
    if not group_id.nil? and not wisp.nil?
      link_to(group_name, wisp_group_access_points_path(wisp, group_id))
    elsif wisp.nil?
      group_name
    end
  end
  
  def select_group_url_if_wisp_loaded
    if wisp_loaded?
      select_group_wisp_path(@wisp)
    else
      select_group_access_points_path
    end
  end
  
  def show_stat(action, count)
    ("<span class='%s'><b>%s:</b> %s</span>" % [action, t(action), count]).html_safe
  end
end

app/views/access_points/_access_point_graphs.html.erb
<%#
# This file is part of the OpenWISP Geographic Monitoring
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<% content_for :after_defaults do %>
    <%= stylesheet_link_tag 'jquery-ui/styles' %>
    <%= javascript_include_tag(
        'highcharts',
        'highcharts.exporting',
        'jquery-ui',
        'owgm.graphs',
        'owgm.activity_graph',
        'owgm.activity_histories_graph',
        'owgm.associated_users_graph',
        'owgm.associated_user_histories_graph'
    ) %>

    <% if @wisp.owums_enabled? %>
        <%= javascript_include_tag(
            'owums.graphs',
            'owums.traffic_graph',
            'owums.logins_graph'
        ) %>
    <% end %>

    <% if @wisp.datawarehouse_enabled? %>
        <%= javascript_include_tag(
            'datawarehouse.activities_graph'
        ) %>
    <% end %>
<% end %>

<% if @access_point.known? %>
    <% if @wisp.owums_enabled? and (auth?(:wisps_viewer) or auth?(:wisp_associated_user_counts_viewer, @wisp)) %>
        <div class="grid_12">
            <div class="box large-graph-container" id="stats-usage">
                <h2>
                    <a href="#" class="toggle<% if CONFIG['ap_stats_collapsed'] %> hidden<% end %>">
                        <%= t(:Usage_stats) %>
                        <span class="arrow" data-show="&#x25BC;" data-hide="&#x25B2;">&#x25BC;</span>
                    </a>
                </h2>

                <div class="container<% if CONFIG['ap_stats_collapsed'] %> hidden<% end %>">
                    <div class="box" id="stats-interval" data-url="<%= wisp_export_stats_path %>">
                        <%= form_tag '', :method => :get do %>
                            <strong><%=t :Interval %></strong>:
                            <%= text_field_tag 'from', l(@from) %>
                            <strong>-</strong>
                            <%= text_field_tag 'to', l(@to) %>
                            <%= hidden_field_tag 'mac', @access_point.common_name %>
                            <button type="submit"><%= t(:Update) %></button>
                        <% end %>
                    </div>

                    <div class="block stats">
                        <div class="block big_graph" id="logins_graph" data-url="<%= wisp_logins_json_path %>">
                            <h5 class="center"><%=t :Loading_data %> <%= image_tag "spinner.gif" %></h5>
                        </div>
                    </div>

                    <div class="block stats">
                        <div class="block big_graph" id="traffic_graph" data-url="<%= wisp_traffic_json_path %>">
                            <h5 class="center"><%=t :Loading_data %> <%= image_tag "spinner.gif" %></h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
            if (!$('#stats-usage .container').is(':hidden')) {
                owumsGraphs.drawLogins();
                owumsGraphs.drawTraffic();
            }
            $('#stats-interval form').submit(function(e){
                e.preventDefault();
                owumsGraphs.drawLogins();
                owumsGraphs.drawTraffic();
            });
        </script>
        <div class="clear"></div>
    <% end %>

    <% if auth?(:wisps_viewer) || auth?(:wisp_activity_histories_viewer, @wisp)%>
        <div class="grid_6">
          <div class="box">
            <h2><%=t :Activity_average_graph %></h2>
            <p class="howto right bold">(<%=t :Click_and_drag_to_zoom_in %>)</p>
            <p class="no_js"><%=t :No_javascript %></p>
            <div id="activity_histories_graph"></div>
            <p>&nbsp;</p>
          </div>
        </div>
    <% end %>

    <% if auth?(:wisps_viewer) || auth?(:wisp_activities_viewer, @wisp)%>
        <div class="grid_6">
          <div class="box">
            <h2><%=t :Activity_graph %></h2>
            <p>&nbsp;</p>
            <p class="no_js"><%=t :No_javascript %></p>
            <div id="activity_graph"></div>
            <p>&nbsp;</p>
          </div>
        </div>
    <% end %>

    <% if @wisp.datawarehouse_enabled? and (auth?(:wisps_viewer) or auth?(:wisp_associated_user_counts_viewer, @wisp)) %>
        <div class="grid_12">
            <div class="box large-graph-container" id="stats-activities">
                <h2>
                    <a href="#" class="toggle<% if CONFIG['ap_stats_collapsed'] %> hidden<% end %>">
                        <%= t(:Activity_average_archive) %>
                        <span class="arrow" data-show="&#x25BC;" data-hide="&#x25B2;">&#x25BC;</span>
                    </a>
                </h2>

                <div class="container<% if CONFIG['ap_stats_collapsed'] %> hidden<% end %>">
                    <div class="box stats-interval" id="activities-interval">
                        <%= form_tag '', :method => :get do %>
                            <strong><%=t :Interval %></strong>:
                            <%= text_field_tag 'paramStartDate', l(@from - 1.month) %>
                            <strong>-</strong>
                            <%= text_field_tag 'paramStopDate', l(@to - 1.month) %>
                            <%= hidden_field_tag 'parammacaddress', @access_point.common_name.upcase %>
                            <button type="submit"><%= t(:Update) %></button>
                        <% end %>
                    </div>

                    <div class="block big_graph stats" id="activities_graph" data-url="<%= wisp_activities_json_path %>">
                        <h5 class="center"><%=t :Loading_data %> <%= image_tag "spinner.gif" %></h5>
                    </div>
                </div>
            </div>
        </div>
        <script>
            if (!$('#stats-activities .container').is(':hidden')) {
                graphs.drawActivityArchive();
            }
            $('#stats-activities form').submit(function(e){
                e.preventDefault();
                graphs.drawActivityArchive();
            });
        </script>
        <div class="clear"></div>
    <% end %>

    <% if @wisp.owmw_enabled? and CONFIG['user_counts_graphs'] %>
        <% if auth?(:wisps_viewer) || auth?(:wisp_associated_user_count_histories_viewer, @wisp)%>
            <div class="grid_6">
              <div class="box">
                <h2><%=t :Associated_users_average_graph %></h2>
                <p class="howto right bold">(<%=t :Click_and_drag_to_zoom_in %>)</p>
                <p class="no_js"><%=t :No_javascript %></p>
                <div id="associated_user_histories_graph"></div>
                <p>&nbsp;</p>
              </div>
            </div>
        <% end %>

        <% if auth?(:wisps_viewer) || auth?(:wisp_associated_user_counts_viewer, @wisp)%>
            <div class="grid_6">
              <div class="box">
                <h2><%=t :Associated_users_graph %></h2>
                <p>&nbsp;</p>
                <p class="no_js"><%=t :No_javascript %></p>
                <div id="associated_user_counts_graph"></div>
                <p>&nbsp;</p>
              </div>
            </div>
        <% end %>
    <% end %>
<% else %>
    <br />
    <h5 class="nodata center"><%=t :No_data_to_display %></h5>
    <br />
<% end %>

app/views/access_points/show.html.erb
<%#
# This file is part of the OpenWISP Geographic Monitoring
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#  $('#clickable_favourite').click(function() { $('#favourite').click() });
#%>

<% content_for :after_defaults do %>
    <%= javascript_include_tag(
						'https://maps.google.com/maps/api/js?sensor=false&v=3.9',
						'gmaps.markermanager',
						'markerclusterer/markerclusterer_compiled.js',
						'owgm.gmaps',
						'jquery.jeditable')
		%>
		
    <%= javascript_tag "$(function(){
				$('#clickable_category').click(function() { $('#category_select').click() });
				$('#clickable_site_description').click(function() { $('#site_description').click() });
				$('#clickable_notes').click(function() { $('#notes').click() });
				$('#clickable_public td').click(function(){
						el = $('#clickable_public .toggle-public');
						owgm.toggleProperty(el.attr('data-href'), function(result){
								el.find('img').attr('src', result.image)
						});
				});

				$('#category_select').live('change', function(){
						if ($(this).find('select').val() == '!new!') {
								$(this).hide();
								$('#category_text').click();
								$('#category_text').show();
						}
				});
				$('#notes').editable('#{wisp_access_point_property_set_url(@wisp, @access_point)}', {
						submitdata: {authenticity_token:'#{form_authenticity_token}'},
						name: 'property_set[notes]', method: 'PUT',
						type: 'textarea', rows: 5,
						submit: '#{t :Ok}', cancel: '#{t :Cancel}',
						tooltip: '#{t :Click_to_edit}',
						placeholder: '#{t :No_notes_available}'
				});
				$('#site_description').editable('#{wisp_access_point_property_set_url(@wisp, @access_point)}', {
						submitdata: {authenticity_token:'#{form_authenticity_token}'},
						name: 'property_set[site_description]', method: 'PUT',
						type: 'textarea', rows: 5,
						submit: '#{t :Ok}', cancel: '#{t :Cancel}',
						tooltip: '#{t :Click_to_edit}',
						placeholder: '#{t :No_notes_available}'
				});
				$('#category_select').editable('#{wisp_access_point_property_set_url(@wisp, @access_point)}', {
						submitdata: {authenticity_token:'#{form_authenticity_token}'},
						name: 'property_set[category]', method: 'PUT',
				type: 'select', data: #{categories_select_data(@wisp, @access_point)},
						callback: function(value, settings) { location.reload(); },
						placeholder: '#{t :None}',
						submit: '#{t :Ok}', cancel: '#{t :Cancel}'
				});
				$('#category_text').editable('#{wisp_access_point_property_set_url(@wisp, @access_point)}', {
						submitdata: {authenticity_token:'#{form_authenticity_token}'},
						name: 'property_set[category]', method: 'PUT',
						submit: '#{t :Ok}', cancel: '#{t :Cancel}', width: 60,
						callback: function(value, settings) { location.reload(); },
						onreset: function() {
								$('#category_text').hide();
								$('#category_select').show();
						}
				});
    });" %>
		
<% end %>

<div class="grid_12">
  <h1 class="mainheading">
		<%=t :Access_point %> “<%= @access_point.hostname %>”
		<a class="toggle-favourite hastip" data-href="<%= toggle_favourite_wisp_access_point_path(@wisp.id, @access_point) %>" title="<%= t(@access_point.favourite? ? :Remove_from_favourites : :Add_to_favourites) %>" data-add="<%= t :Add_to_favourites %>"  data-remove="<%= t :Remove_from_favourites %>">
				<%= image_tag(@access_point.favourite? ? 'star.png' : 'star-off.png') %>
		</a>
	</h1>

  <div class="grid_6">
    <div class="box">
      <h2><%=t :Map %></h2>
      <br />
      <div id="gmap_show" data-lat="<%= @access_point.lat %>" data-lng="<%= @access_point.lng %>">
        <p class="no_js"><%=t :No_javascript %></p>
      </div>
      <br />
    </div>
  </div>

  <div class="grid_6">
    <div class="box" id="access-point-info">
      <%= render :partial => 'access_point_info' %>
    </div>
  </div>

  <div class="clear"></div>
		
	<%= render :partial => 'access_point_last_logins' %>
	
  <%= render :partial => 'access_point_graphs' %>

  <div class="grid_12">
    <div class="box">
      <%= render :partial => 'access_point_more_info' %>
    </div>
  </div>
</div>

<script>
		owgm.initSelectGroup("<%= wisp_access_point_select_group_url(@wisp, @access_point) %>");
		owgm.initFavourite();
		// load all markers in the background
		gmaps.loadMarkersFromJSON('<%= wisp_access_points_url(@wisp) %>?simple=true');
</script>