config/routes.rb
Owgm::Application.routes.draw do

  devise_for :users
  resources :users

  resources :access_points, :only => [:index] do
    collection do
      post 'change_property' => 'access_points#batch_change_property'
      get 'select_group' => 'access_points#batch_select_group'
    end
  end

  resources :configurations, :only => [:edit, :update]

  resources :wisps, :only => :index do

    match 'reset_favourites' => 'access_points#reset_favourites', :as => :reset_favourites
    match 'access_points_favourite' => 'access_points#index', :as => :access_points_favourite, :defaults => { :filter => 'favourite' }

    member do
      get 'select_group' => 'access_points#batch_select_group'
    end

    match 'groups' => 'groups#list', :as => :groups, :via => [:get]
    match 'groups/:group_id/access_points' => 'access_points#index', :as => :group_access_points, :via => [:get]

    resources :access_points, :only => [:index, :show] do

      resource :property_set, :only => :update

      member do
        post 'toggle_public'
        post 'toggle_favourite'
        get 'last_logins'
      end
    end

    resources :activity_histories, :only => :index

    match 'access_points/:access_point_id/activities' => 'activities#show', :as => :access_point_activities
    match 'access_points/:access_point_id/activity_histories' => 'activity_histories#show', :as => :access_point_activity_histories
    match 'access_points/:access_point_id/associated_user_counts' => 'associated_user_counts#show',
          :as => :associated_user_counts
    match 'access_points/:access_point_id/associated_user_count_histories' => 'associated_user_count_histories#show',
          :as => :associated_user_count_histories
    match 'availability_report' => 'activity_histories#index', :as => :availability_report
    match 'export' => 'activity_histories#export', :as => :export, :via => [:post]
    match 'send_report' => 'activity_histories#send_report', :as => :send_report

    match 'access_points/:access_point_id/select_group' => 'access_points#select_group', :as => :access_point_select_group, :via => [:get]
    match 'access_points/:access_point_id/change_group/:group_id' => 'access_points#change_group', :as => :access_point_change_group, :via => [:post]
    match 'access_points/:access_point_id/edit_ap_alert_settings' => 'access_points#edit_ap_alert_settings', :as => :access_point_edit_ap_alert_settings, :via => [:post]

    match 'stats/logins.json' => 'stats#logins', :as => :logins_json, :via => [:get]
    match 'stats/traffic.json' => 'stats#traffic', :as => :traffic_json, :via => [:get]
    match 'stats/export' => 'stats#export', :as => :export_stats, :via => [:post]

    match 'stats/activities.json' => 'stats#activities', :as => :activities_json, :via => [:get]
  end

  resources :groups, :only => [:index, :new, :edit, :create, :update, :destroy] do
    member do
      post 'toggle_monitor'
      post 'toggle_count_stats'
    end
  end

  match 'wisps/' => 'wisps#index', :via => [:get]

  root :to => "application#index"

end

app/views/layouts/access_denied.html.erb
<div class="grid_12">
  <div class="box">
    <h1 class="maingheading"><%= t :Access_denied %></h1>
    <p><%= t :Missing_required_permissions %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<%#
# This file is part of the OpenWISP Geographic Monitoring
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<!DOCTYPE html>
<html>
<head>
  <title>OWGM</title>

  <link rel="shortcut icon" href="<%= image_path 'favicon.png' %>" />

  <%= stylesheet_link_tag '960/css/reset',
                          '960/css/text',
                          '960/css/grid',
                          '960/css/layout',
                          '960/css/nav',
                          '960/css/notification',
                          'application'
  %>

  <%= for_ie :version => '6' do %>
      <%= stylesheet_link_tag '960/css/ie6' %>
  <% end %>

  <%= for_ie :if => 'gte', :version => '7' do %>
      <%= stylesheet_link_tag '960/css/ie' %>
  <% end %>

  <%= javascript_include_tag :defaults, 'jquery.observe', 'jquery.simpletip.min.js' %>

  <%= content_for :after_defaults %>

  <%= content_for :js_templates %>

  <%= csrf_meta_tag %>
</head>
<body>
<div class="container_12" id="container">
  <div class="grid_12">
    <div id="header">
      <h1 id="branding"><a href="<%= root_path %>">Geographic Monitoring</a></h1>
      <div id="lang"><%= link_to_locale 'it' %> <%= link_to_locale 'en' %></div>
    </div>
    <% if user_signed_in? %>
    <nav>
      <ul class="nav main" id="main-nav">
        <li class="first">
          <a href="<%= wisps_path %>" title="<%= t :Wisp_list %>"<%= active_link_if wisps_path, '/access_points', '/groups' %>>
            <%= t :Wisp %><% if @wisps_menu.length > 0 %><span>&#x25BE;</span><% end %>
          </a>
          <% if @wisps_menu.length > 0 %>
          <ul class="second-level">
          <% @wisps_menu.each do |wisp| %>
            <li>
              <a href="<%= wisp_access_points_url(wisp) %>"><%= wisp.name %><span>&raquo;</span></a>
              <ul class="third-level">
                <li><a href="<%= wisp_availability_report_path(wisp) %>"><%= t :Availability_report %></a></li>
              </ul>
            </li>
          <% end %>
          </ul>
          <% end %>
        </li>
        <% if @wisps_menu.length > 0 %>
        <li>
          <a <% if auth?(:wisps_viewer) %>href="<%= access_points_url %>" title="<%= t(:Show_all_access_points) %>"<% end %> <%= active_link_if access_points_path %>><%= t :Access_points %><span>&#x25BE;</span></a>
          <ul class="second-level">
            <% @wisps_menu.each do |wisp| %>
            <li>
              <a href="<%= wisp_access_points_url(wisp) %>"><%= wisp.name %><span>&raquo;</span></a>
              <ul class="third-level">
                <li><a href="<%= wisp_access_points_url(wisp) %>"><%= t :Access_points_of_this_wisp %></a></li>
                <li><a href="<%= wisp_groups_url(wisp) %>"><%= t :Groups_of_this_wisp %></a></li>
                <li><a href="<%= wisp_access_points_favourite_url(wisp) %>"><%= t :Favourites %></a></li>
              </ul>
            </li>
            <% end %>
          </ul>
        </li>
        <% end %>
        <% if auth?(:wisps_viewer) or auth?(:wisp_access_points_viewer) %>
        <li>
          <a href="<%= groups_url %>" title="<%= t :Group_list %>"<%= active_link_if groups_path, '/access_points' %>><%= t :Groups %></a>
        </li>
        <% end %>
        <% if auth? :wisps_viewer %>
        <li>
          <a href="<%= users_url %>" title="<%= t :User_management %>"<%= active_link_if users_path %>><%= t :Users %></a>
        </li>        
        <li>
          <a href="<%= edit_configuration_path('owmw') %>" title="<%= t(:Configure_owmw) %>"<%= active_link_if edit_configuration_path('owmw') %>><%= t(:Configure_owmw) %></a>
        </li>
        <% end %>
      </ul>
    </nav>
    
    <ul class="nav main" id="breadcrumbs">
      <%= render_breadcrumbs :tag => :li, :separator => '<li class="spacer">&raquo</li>' %>
      <li id="logout"><%= t :logged_as %> <b><%= current_user.username %></b> &nbsp; - &nbsp; <%= link_to t(:Sign_out), destroy_user_session_path %></li>
    </ul>
    <% end %>
    <% if flash[:notice] %>
    <div class="message notice">
      <%= flash[:notice] %> <a class="close">&times;&nbsp;chiudi</a>
    </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="message alert">
      <%= flash[:alert] %> <a class="close">&times;&nbsp;chiudi</a>
    </div>
    <% end %>
  </div>

  <div class="clear"></div>
  <br />
  <%= yield %>
  <div class="clear"></div>
</div>

<!--[if lte IE 8]>
  <%= javascript_include_tag 'ie8/warning.js' %>
  <script>$(window).load(function(){e("<%= javascript_path("ie8").sub('.js', '/') %>")})</script>
<![endif]-->
</body>
</html>